--------------------------------------------------------
--  File created - Sunday-September-10-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "SYS"."EMPLOYEE" 
   (	"ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(10 BYTE), 
	"LAST_NAME" VARCHAR2(10 BYTE), 
	"SALARY" NUMBER(10,2), 
	"DEPARTMENT_NO" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.EMPLOYEE
SET DEFINE OFF;
Insert into SYS.EMPLOYEE (ID,FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_NO) values (1,'ABC','CBA',232.1,60);
Insert into SYS.EMPLOYEE (ID,FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_NO) values (2,'DEF','FED',2323.12,70);
Insert into SYS.EMPLOYEE (ID,FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_NO) values (3,'GHI','IHG',23132.1,80);
Insert into SYS.EMPLOYEE (ID,FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_NO) values (4,'JKL','LKJ',2326.1,90);
Insert into SYS.EMPLOYEE (ID,FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_NO) values (5,'NOP','PON',5232.1,100);
