light:
  - platform: rgb
    name: "RGB Test"
    red: Red
    green: Green
    blue: Blue

output:
  - platform: esp8266_pwm
    id: Red
    pin: D1

  - platform: esp8266_pwm
    id: Green
    pin: D2

  - platform: esp8266_pwm
    id: Blue
    pin: D3
